version: 2.1

# Define jobs
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: |
          echo $API_KEY

  # Test job with pipeline execution within
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: |
          # Execute the desired pipeline within the test job
          python /tests/reachability_test.py
          
# Workflow to orchestrate job execution
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build  # Ensure 'test' job runs after 'build' finishes
