version: 2.1

# Define jobs
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: |
          echo $API_KEY

  test:
    docker:
      - image: cimg/python:3.9  
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            ls -la
            pwd
            python -m venv venv
            . venv/bin/activate
            ls -la
            pwd
            cd /home/circleci/project/weather-app/app
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')

# Workflow to orchestrate job execution
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build  # Ensure 'test' job runs after 'build' finishes
