version: 2.1
orbs:
  discord: antonioned/discord@0.1.0
  aws-eks: circleci/aws-eks@1.0.0
  kubernetes: circleci/kubernetes@0.11.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image With Version Scheme
          command: |
            cd /home/circleci/project/weather-app/app
            docker build -t registry.gitlab.com/team1414207/docker-image:latest .
            docker tag registry.gitlab.com/team1414207/docker-image:latest registry.gitlab.com/team1414207/docker-image:1.0.$CIRCLE_SHA1
      - run:
          name: Push Docker Image
          command: |
            echo $GITLAB_REGISTRY | docker login registry.gitlab.com -u your-gitlab-username --password-stdin
            docker push registry.gitlab.com/team1414207/docker-image:latest
            docker push registry.gitlab.com/team1414207/docker-image:1.0.$CIRCLE_SHA1

  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            cd /home/circleci/project/weather-app/app
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            cd /home/circleci/project/weather-app/tests
            python reachability_test.py
      - discord/status:
          fail_only: false
          failure_message: "**${CIRCLE_USERNAME}**'s build: **${CIRCLE_JOB}** failed."
          success_message: "**${CIRCLE_USERNAME}** deployed api to prod."
          webhook: "${DISCORD_STATUS_WEBHOOK}"

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
