version: 2.1

# Define jobs
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      
    steps:
      - Build Docker Image With Version Schem 
      - run: |
          cd /home/circleci/project/weather-app/app
          
          docker build -t kupidun/weather-circleci:latest .
          docker tag kupidun/kupidun/weather-circleci:latest kupidun/kupidun/weather-circleci:1.0.$CIRCLE_SHA1

  test:
    docker:
      - image: cimg/python:3.9  
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            ls -la
            pwd
            python -m venv venv
            . venv/bin/activate
            ls -la
            pwd
            cd /home/circleci/project/weather-app/app
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
          
            . venv/bin/activate
            cd /home/circleci/project/weather-app/tests
            python reachability_test.py

# Workflow to orchestrate job execution
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build  # Ensure 'test' job runs after 'build' finishes
