COUNTRIES = {"united states": "US",
             "afghanistan": "AF",
             "albania": "AL",
             "algeria": "DZ",
             "american samoa": "AS",
             "andorra": "AD",
             "angola": "AO",
             "anguilla": "AI",
             "antigua and barbuda": "AG",
             "argentina": "AR",
             "armenia": "AM",
             "aruba": "AW",
             "australia": "AU",
             "austria": "AT",
             "azerbaijan": "AZ",
             "bahamas": "BS",
             "bahrain": "BH",
             "bangladesh": "BD",
             "barbados": "BB",
             "belarus": "BY",
             "belgium": "BE",
             "belize": "BZ",
             "benin": "BJ",
             "bermuda": "BM",
             "bhutan": "BT",
             "bolivia": "BO",
             "bosnia and herzegovina": "BA",
             "botswana": "BW",
             "brazil": "BR",
             "brunei": "BN",
             "bulgaria": "BG",
             "burkina faso": "BF",
             "burundi": "BI",
             "cambodia": "KH",
             "cameroon": "CM",
             "canada": "CA",
             "cape verde": "CV",
             "cayman islands": "KY",
             "central african republic": "CF",
             "chad": "TD",
             "chile": "CL",
             "china": "CN",
             "christmas island": "CX",
             "cocos islands": "CC",
             "colombia": "CO",
             "comoros": "KM",
             "congo": "CG",
             "democratic republic of the congo": "CD",
             "cook islands": "CK",
             "costa rica": "CR",
             "cote divoire": "CI",
             "croatia": "HR",
             "cuba": "CU",
             "cyprus": "CY",
             "czech republic": "CZ",
             "denmark": "DK",
             "djibouti": "DJ",
             "dominica": "DM",
             "dominican republic": "DO",
             "east timor": "TP",
             "ecuador": "EC",
             "egypt": "EG",
             "el salvador": "SV",
             "equatorial guinea": "GQ",
             "eritrea": "ER",
             "estonia": "EE",
             "ethiopia": "ET",
             "falkland islands": "FK",
             "malvinas": "FK",
             "faroe islands": "FO",
             "fiji": "FJ",
             "finland": "FI",
             "france": "FR",
             "french guiana": "GF",
             "french polynesia": "PF",
             "french s. territories": "TF",
             "gabon": "GA",
             "gambia": "GM",
             "georgia": "GE",
             "germany": "DE",
             "deutschland": "DE",
             "ghana": "GH",
             "gibraltar": "GI",
             "greece": "GR",
             "greenland": "GL",
             "grenada": "GD",
             "guadeloupe": "GP",
             "guam": "GU",
             "guatemala": "GT",
             "guinea": "GN",
             "guinea-bissau": "GW",
             "guyana": "GY",
             "haiti": "HT",
             "honduras": "HN",
             "hong kong": "HK",
             "hungary": "HU",
             "iceland": "IS",
             "india": "IN",
             "indonesia": "ID",
             "iran": "IR",
             "iraq": "IQ",
             "ireland": "IE",
             "israel": "IL",
             "italy": "IT",
             "jamaica": "JM",
             "japan": "JP",
             "jordan": "JO",
             "kazakhstan": "KZ",
             "kenya": "KE",
             "kiribati": "KI",
             "north korea": "KP",
             "south korea": "KR",
             "kosovo": "XK",
             "kuwait": "KW",
             "kyrgyzstan": "KG",
             "laos": "LA",
             "latvia": "LV",
             "lebanon": "LB",
             "lesotho": "LS",
             "liberia": "LR",
             "libya": "LY",
             "liechtenstein": "LI",
             "lithuania": "LT",
             "luxembourg": "LU",
             "macau": "MO",
             "macedonia": "MK",
             "madagascar": "MG",
             "malawi": "MW",
             "malaysia": "MY",
             "maldives": "MV",
             "mali": "ML",
             "malta": "MT",
             "marshall islands": "MH",
             "martinique": "MQ",
             "mauritania": "MR",
             "mauritius": "MU",
             "mayotte": "YT",
             "mexico": "MX",
             "micronesia": "FM",
             "moldova": "MD",
             "monaco": "MC",
             "mongolia": "MN",
             "montserrat": "MS",
             "montenegro": "ME",
             "morocco": "MA",
             "mozambique": "MZ",
             "myanmar": "MM",
             "namibia": "NA",
             "nauru": "NR",
             "nepal": "NP",
             "netherlands": "NL",
             "netherlands antilles": "AN",
             "new caledonia": "NC",
             "new zealand": "NZ",
             "nicaragua": "NI",
             "niger": "NE",
             "nigeria": "NG",
             "niue": "NU",
             "norfolk island": "NF",
             "mariana islands": "MP",
             "norway": "NO",
             "oman": "OM",
             "pakistan": "PK",
             "palau": "PW",
             "panama": "PA",
             "papua new guinea": "PG",
             "paraguay": "PY",
             "peru": "PE",
             "philippines": "PH",
             "pitcairn": "PN",
             "poland": "PL",
             "portugal": "PT",
             "puerto rico": "PR",
             "qatar": "QA",
             "reunion": "RE",
             "romania": "RO",
             "russia": "RU",
             "rwanda": "RW",
             "saint kitts and nevis": "KN",
             "saint lucia": "LC",
             "saint vincent and the grenadines": "VC",
             "samoa": "WS",
             "san marino": "SM",
             "sao tome": "ST",
             "saudi arabia": "SA",
             "senegal": "SN",
             "serbia": "RS",
             "seychelles": "SC",
             "sierra leone": "SL",
             "singapore": "SG",
             "slovakia": "SK",
             "slovenia": "SI",
             "solomon islands": "SB",
             "somalia": "SO",
             "south africa": "ZA",
             "spain": "ES",
             "sri lanka": "LK",
             "saint helena": "SH",
             "saint pierre": "PM",
             "sudan": "SD",
             "suriname": "SR",
             "swaziland": "SZ",
             "sweden": "SE",
             "switzerland": "CH",
             "syria": "SY",
             "taiwan": "TW",
             "tajikistan": "TJ",
             "tanzania": "TZ",
             "thailand": "TH",
             "togo": "TG",
             "tokelau": "TK",
             "tonga": "TO",
             "trinidad and tobago": "TT",
             "tunisia": "TN",
             "turkey": "TR",
             "turkmenistan": "TM",
             "tuvalu": "TV",
             "uganda": "UG",
             "ukraine": "UA",
             "united arab emirates": "AE",
             "united kingdom": "UK",
             "uruguay": "UY",
             "uzbekistan": "UZ",
             "vanuatu": "VU",
             "vatican city": "VA",
             "venezuela": "VE",
             "vietnam": "VN",
             "virgin islands": "VI",
             "western sahara": "EH",
             "yemen": "YE",
             "yugoslavia": "YU",
             "zaire": "ZR",
             "zambia": "ZM",
             "zimbabwe": "ZW"}

CAPITALS = {
    "afghanistan": "Kabul",
    "albania": "Tirana",
    "algeria": "Algiers",
    "american samoa": "Pago Pago",
    "andorra": "Andorra la Vella",
    "angola": "Luanda",
    "anguilla": "The Valley",
    "antigua and barbuda": "Saint Johns",
    "argentina": "Buenos Aires",
    "armenia": "Yerevan",
    "aruba": "Oranjestad",
    "australia": "Canberra",
    "austria": "Vienna",
    "azerbaijan": "Baku",
    "bahamas": "Nassau",
    "bahrain": "Manama",
    "bangladesh": "Dhaka",
    "barbados": "Bridgetown",
    "belarus": "Minsk",
    "belgium": "Brussels",
    "belize": "Belmopan",
    "benin": "Porto-Novo",
    "bermuda": "Hamilton",
    "bhutan": "Thimphu",
    "bolivia": "La Paz, Sucre",
    "bosnia and herzegovina": "Sarajevo",
    "botswana": "Gaborone",
    "brazil": "Brasilia",
    "brunei": "Bandar Seri Begawan",
    "bulgaria": "Sofia",
    "burkina faso": "Ouagadougou",
    "burundi": "Bujumbura",
    "cambodia": "Phnom Penh",
    "cameroon": "Yaounde",
    "canada": "Ottawa",
    "cape verde": "Praia",
    "cayman islands": "George Town",
    "central african republic": "Bangui",
    "chad": "NDjamena",
    "chile": "Santiago",
    "china": "Beijing",
    "christmas island": "Flying Fish Cove",
    "cocos islands": "West Island",
    "colombia": "Bogota",
    "comoros": "Moroni",
    "congo": "Brazzaville",
    "democratic republic of the congo": "Kinshasa",
    "cook islands": "Avarua",
    "costa rica": "San Jose",
    "cote divoire": "Yamoussoukro",
    "croatia": "Zagreb",
    "cuba": "Havana",
    "cyprus": "Nicosia",
    "czech republic": "Prague",
    "denmark": "Copenhagen",
    "djibouti": "Djibouti",
    "dominica": "Roseau",
    "dominican republic": "Santo Domingo",
    "east timor": "Dili",
    "ecuador": "Quito",
    "egypt": "Cairo",
    "el salvador": "San Salvador",
    "equatorial guinea": "Malabo",
    "eritrea": "Asmara",
    "estonia": "Tallinn",
    "ethiopia": "Addis Ababa",
    "falkland islands": "Stanley",
    "faroe islands": "Torshavn",
    "fiji": "Suva",
    "finland": "Helsinki",
    "france": "Paris",
    "french guiana": "Cayenne",
    "french polynesia": "Papeete",
    "french s. territories": "Saint Pierre",
    "gabon": "Libreville",
    "gambia": "Banjul",
    "georgia": "Tbilisi",
    "germany": "Berlin",
    "deutschland": "Berlin",
    "ghana": "Accra",
    "gibraltar": "Catalan Bay",
    "greece": "Athens",
    "grenada": "Saint Georges",
    "greenland": "Nuuk",
    "guadeloupe": "Basse-Terre",
    "guam": "Hagatna",
    "guatemala": "Guatemala City",
    "guinea": "Conakry",
    "guinea-bissau": "Bissau",
    "guyana": "Georgetown",
    "haiti": "Port-au-Prince",
    "honduras": "Tegucigalpa",
    "hong kong": "Victoria",
    "hungary": "Budapest",
    "iceland": "Reykjavik",
    "india": "New Delhi",
    "indonesia": "Jakarta",
    "iran": "Tehran",
    "iraq": "Baghdad",
    "ireland": "Dublin",
    "israel": "Jerusalem",
    "italy": "Rome",
    "jamaica": "Kingston",
    "japan": "Tokyo",
    "jordan": "Amman",
    "kazakhstan": "Astana",
    "kenya": "Nairobi",
    "kiribati": "Tarawa Atoll",
    "north korea": "Pyongyang",
    "south korea": "Seoul",
    "kosovo": "Pristina",
    "kuwait": "Kuwait City",
    "kyrgyzstan": "Bishkek",
    "laos": "Vientiane",
    "latvia": "Riga",
    "lebanon": "Beirut",
    "lesotho": "Maseru",
    "liberia": "Monrovia",
    "libya": "Tripoli",
    "liechtenstein": "Vaduz",
    "lithuania": "Vilnius",
    "luxembourg": "Luxembourg",
    "macau": "Macau",
    "macedonia": "Skopje",
    "madagascar": "Antananarivo",
    "malawi": "Lilongwe",
    "malaysia": "Kuala Lumpur",
    "maldives": "Male",
    "mali": "Bamako",
    "malta": "Valletta",
    "malvinas": "Stanley",
    "mariana islands": "Saipan",
    "marshall islands": "Majuro",
    "martinique": "Fort-de-France",
    "mauritania": "Nouakchott",
    "mauritius": "Port Louis",
    "mayotte": "Mamoudzou",
    "mexico": "Mexico City",
    "micronesia": "Palikir",
    "moldova": "Chisinau",
    "monaco": "Monaco",
    "mongolia": "Ulaanbaatar",
    "montserrat": "Plymouth",
    "montenegro": "Podgorica",
    "morocco": "Rabat",
    "mozambique": "Maputo",
    "myanmar": "Naypyidaw",
    "namibia": "Windhoek",
    "nauru": "Yaren District",
    "nepal": "Kathmandu",
    "netherlands": "Amsterdam",
    "netherlands antilles": "Willemstad",
    "new caledonia": "Noumea",
    "new zealand": "Wellington",
    "nicaragua": "Managua",
    "niger": "Niamey",
    "nigeria": "Abuja",
    "niue": "Alofi",
    "norfolk island": "Norwich",
    "norway": "Oslo",
    "oman": "Muscat",
    "pakistan": "Islamabad",
    "palau": "Melekeok",
    "panama": "Panama City",
    "papua new guinea": "Port Moresby",
    "paraguay": "Asuncion",
    "peru": "Lima",
    "philippines": "Manila",
    "pitcairn": "Adamstown",
    "poland": "Warsaw",
    "portugal": "Lisbon",
    "puerto rico": "San Juan",
    "qatar": "Doha",
    "reunion": "Saint-Denis",
    "romania": "Bucharest",
    "russia": "Moscow",
    "rwanda": "Kigali",
    "saint kitts and nevis": "Basseterre",
    "saint lucia": "Castries",
    "saint vincent and the grenadines": "Kingstown",
    "samoa": "Apia",
    "san marino": "San Marino",
    "sao tome": "Sao Tome",
    "saudi arabia": "Riyadh",
    "senegal": "Dakar",
    "serbia": "Belgrade",
    "seychelles": "Victoria",
    "sierra leone": "Freetown",
    "singapore": "Singapore",
    "slovakia": "Bratislava",
    "slovenia": "Ljubljana",
    "solomon islands": "Honiara",
    "somalia": "Mogadishu",
    "south africa": "Pretoria, Cape Town, Bloemfontein",
    "spain": "Madrid",
    "sri lanka": "Colombo, Sri Jayewardenepura Kotte",
    "saint helena": "Jamestown",
    "saint pierre": "Saint-Pierre",
    "sudan": "Khartoum",
    "suriname": "Paramaribo",
    "swaziland": "Mbabane",
    "sweden": "Stockholm",
    "switzerland": "Bern",
    "syria": "Damascus",
    "taiwan": "Taipei",
    "tajikistan": "Dushanbe",
    "tanzania": "Dodoma",
    "thailand": "Bangkok",
    "togo": "Lome",
    "tokelau": "Atafu",
    "tonga": "Nukualofa",
    "trinidad and tobago": "Port-of-Spain",
    "tunisia": "Tunis",
    "turkey": "Ankara",
    "turkmenistan": "Ashgabat",
    "tuvalu": "Funafuti",
    "uganda": "Kampala",
    "ukraine": "Kyiv",
    "united arab emirates": "Abu Dhabi",
    "united kingdom": "London",
    "united states": "Washington D.C.",
    "uruguay": "Montevideo",
    "uzbekistan": "Tashkent",
    "vanuatu": "Port-Vila",
    "vatican city": "Vatican City",
    "venezuela": "Caracas",
    "vietnam": "Hanoi",
    "virgin islands": "Charlotte Amalie",
    "western sahara": "Laayoune",
    "yemen": "Sanaa",
    "yugoslavia": "Belgrade",
    "zaire": "Kinshasa",
    "zambia": "Lusaka",
    "zimbabwe": "Harare"
}


if __name__ == "__main__":
    # Checks if any capitals / country codes are missing
    for country in COUNTRIES.keys():
        if country not in CAPITALS.keys():
            print(country)

    print("--------------------------------------------------------")

    for country in CAPITALS.keys():
        if country not in COUNTRIES.keys():
            print(country)
